server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

zuul:
  routes:
    country:
      path: /country/**
      serviceId: country-service
    organisation:
      path: /organisation/**
      serviceId: organisation-service